# Generated by Django 4.2.20 on 2025-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_forumpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('HARVEST', 'Harvest'), ('MAINTENANCE', 'Maintenance'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20),
        ),
    ]
