# Generated by Django 4.2.20 on 2025-10-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("garden", "0005_profile_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="receives_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TASK", "Task Update"),
                            ("SOCIAL", "Social Activity"),
                            ("FORUM", "Forum Activity"),
                            ("WEATHER", "Weather Alert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
