# Generated by Django 4.2.20 on 2025-10-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_profile_receives_notifications_notification'),
        ('garden', '0007_comment_is_deleted_forumpost_is_deleted_report'),
    ]

    operations = [
    ]
