# Generated by Django 4.2.20 on 2025-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_image_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_mime_type',
            field=models.CharField(default='image/jpeg', max_length=100),
        ),
    ]
