# Generated by Django 4.2.20 on 2025-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_gardenevent_eventattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenevent',
            name='event_category',
            field=models.CharField(choices=[('WORKSHOP', 'Workshops and Practice'), ('POTLUCK', 'Potluck / Picnic'), ('EXCHANGE', 'Garden Exchange'), ('TREASURE_HUNT', 'Treasure Hunt'), ('PHOTOGRAPHY', 'Photography Day'), ('CELEBRATION', 'Celebration'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
