# Generated by Django 4.2.20 on 2025-11-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_gardenevent_eventattendance'),
        ('garden', '0012_populate_badges'),
    ]

    operations = [
    ]
