# Generated by Django 4.2.20 on 2025-11-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0012_gardenevent_event_category'),
        ('garden', '0014_notification_link'),
    ]

    operations = [
    ]
