# Generated by Django 4.2.20 on 2025-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
