# Generated by Django 4.2.20 on 2025-12-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0016_profile_is_private'),
        ('garden', '0018_garden_latitude_garden_longitude'),
    ]

    operations = [
    ]
