# Generated by Django 4.2.20 on 2025-12-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0016_garden_latitude_garden_longitude"),
        ("garden", "0018_garden_latitude_garden_longitude"),
    ]

    operations = []
