# Generated by Django 4.2.20 on 2025-12-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0019_forumpostlike_commentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="best_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="best_answer_for",
                to="garden.comment",
            ),
        ),
    ]
