# Generated by Django 4.2.20 on 2025-12-14 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("garden", "0025_garden_hide_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
